server:
  port: 8081
spring:
  cloud:
    stream:
      function:
        definition: supply
      bindings:
        supply-out-0:
          destination: topic
      dapr:
        bindings:
          supply-out-0:
            producer:
              pubsubName: pubsub
              sidecarIp: 127.0.0.1
              grpcPort: 50001
              sync: false
              sendTimeout: 10000
              metadata:
                ttlInSeconds: 60
                rawPayload: false

